# Generated by Django 3.2.9 on 2022-07-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='children',
            field=models.CharField(max_length=100, null=True, verbose_name='Дети'),
        ),
        migrations.AddField(
            model_name='actor',
            name='location',
            field=models.CharField(max_length=200, null=True, verbose_name='Место рождения'),
        ),
        migrations.AddField(
            model_name='actor',
            name='parents',
            field=models.CharField(max_length=100, null=True, verbose_name='Родители'),
        ),
        migrations.AddField(
            model_name='actor',
            name='partner',
            field=models.CharField(max_length=100, null=True, verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Слоган'),
        ),
    ]
